---
apiVersion: v1
kind: Namespace
metadata:
  name: $KCM_NAMESPACE
  labels:
    app.kubernetes.io/instance: kcm-system
    app.kubernetes.io/part-of: k0rdent
    app.kubernetes.io/version: $KCM_VERSION

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kcm
  namespace: $KCM_NAMESPACE
spec:
  interval: 5m0s
  url: $KCM_OCI_REPOSITORY
  ref:
    tag: $KCM_VERSION

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kcm
  namespace: $KCM_NAMESPACE
spec:
  chartRef:
    kind: OCIRepository
    name: kcm
    namespace: $KCM_NAMESPACE
  interval: 10m
  values:
    flux2:
      enabled: false
    cert-manager:
      enabled: $KCM_CERTMANAGER_ENABLED

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hmc-operator-interaction
  namespace: $FLUX_NAMESPACE
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/instance: kcm-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: kcm
    ports:
    - port: http
  podSelector:
    matchLabels:
      app: source-controller
  policyTypes:
  - Ingress