---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k0rdent-configuration
  namespace: {{ .flux.namespace }}
spec:
  interval: 1m0s
  ref:
    branch: {{ .flux.github.branch }}
  url: https://github.com/{{ .flux.github.username }}/{{ .flux.github.repository }}.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k0rdent-platform
  namespace: {{ .flux.namespace }}
spec:
  interval: 10m0s
  path: ./management/{{ $environmentPath }}k0rdent/platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .flux.namespace }}
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: managements.k0rdent.mirantis.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: accessmanagements.k0rdent.mirantis.com
    - apiVersion: apps/v1
      kind: Deployment
      name: kcm-controller-manager
      namespace: {{ .kcm.namespace }}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k0rdent-configuration
  namespace: {{ .flux.namespace }}
spec:
  interval: 10m0s
  path: ./management/{{ $environmentPath }}k0rdent/configuration
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .flux.namespace }}
  dependsOn:
    - name: k0rdent-platform

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-credentials
  namespace: {{ .flux.namespace }}
spec:
  interval: 10m0s
  path: ./credentials{{ $environmentPath }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .flux.namespace }}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-deployments
  namespace: {{ .flux.namespace }}
spec:
  interval: 10m0s
  path: ./clusters{{ $environmentPath }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .flux.namespace }}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: global-services
  namespace: {{ .flux.namespace }}
spec:
  interval: 10m0s
  path: ./global-services{{ $environmentPath }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .flux.namespace }}