---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k0rdent-configuration
spec:
  interval: 1m0s
  ref:
    branch: main
  url: "provide-a-valid-url" # We've set a dummy value here to make sure the user has to override it
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management
spec:
  interval: 10m0s
  path: ./management
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-credentials
spec:
  interval: 10m0s
  path: ./credentials
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-deployments
spec:
  interval: 10m0s
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: global-services
spec:
  interval: 10m0s
  path: ./global-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
