---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k0rdent-configuration
  namespace: $FLUX_NAMESPACE
spec:
  interval: 1m0s
  ref:
    branch: $GITHUB_REPO_BRANCH
  url: https://github.com/$GITHUB_USERNAME/$GITHUB_REPO_NAME.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management
  namespace: $FLUX_NAMESPACE
spec:
  interval: 10m0s
  path: ./management
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: $FLUX_NAMESPACE

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-credentials
  namespace: $FLUX_NAMESPACE
spec:
  interval: 10m0s
  path: ./credentials
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: $FLUX_NAMESPACE

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-deployments
  namespace: $FLUX_NAMESPACE
spec:
  interval: 10m0s
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: $FLUX_NAMESPACE

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: global-services
  namespace: $FLUX_NAMESPACE
spec:
  interval: 10m0s
  path: ./global-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: $FLUX_NAMESPACE